version: "3"
services:
  minio1:
    image: "minio/minio:latest"
    volumes:
      - "data1:/data"
    expose:
      - "9000"
    ports:
      - "9001:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: "server http://minio{1...4}/data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: "30s"
      timeout: "20s"
      retries: 3
    networks:
      - "net"
  minio2:
    image: "minio/minio:latest"
    volumes:
      - "data2:/data"
    expose:
      - "9000"
    ports:
      - "9002:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: "server http://minio{1...4}/data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: "30s"
      timeout: "20s"
      retries: 3
    networks:
      - "net"
  minio3:
    image: "minio/minio:latest"
    volumes:
      - "data3:/data"
    expose:
      - "9000"
    ports:
      - "9003:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
    command: "server http://minio{1...4}/data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: "30s"
      timeout: "20s"
      retries: 3
    networks:
      - "net"
  minio4:
    image: "minio/minio:latest"
    volumes:
      - "data4:/data"
      - "./minio_access1.log:/logs/access.log"
    expose:
      - "9000"
    ports:
      - "9004:9000"
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY}"
      MINIO_HTTP_TRACE: "/logs/access.log"
    command: "server http://minio{1...4}/data"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: "30s"
      timeout: "20s"
      retries: 3
    networks:
      - "net"
  nginx:
    image: "nginx:latest"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx_log:/var/log/nginx"
    ports:
      - "9000:9000"
    depends_on:
      - "minio1"
      - "minio2"
      - "minio3"
      - "minio4"
    networks:
      - "net"
networks:
  net:
volumes:
  data1:
  data2:
  data3:
  data4:
