version: "3.3"
services:
  neo4j:
    image: neo4j:3.5.5
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./import:/var/lib/neo4j/import
      - ./plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/neo4j_
    ports:
      - "7474:7474"
      - "7687:7687"
