version: "3.3"
services:
  neo4j:
    image: neo4j:latest
    container_name: "neo4j"
    volumes:
      - "neo4j_v:/data"
      - "./logs:/logs"
      - "./import:/var/lib/neo4j/import"
      - "./plugins:/plugins"
    environment:
      - NEO4J_AUTH=neo4j/neo4j_
    networks: 
      - "neo4j_n"
    ports:
      - "7474:7474"
      - "7687:7687"
networks:
  neo4j_n:
volumes:
  neo4j_v:
