Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |box|
		box.memory = 256
		box.cpus = 1
	end

	config.vm.define "debian_buster1" do |debian_buster1|
		debian_buster1.vm.hostname = 'debian01'
		debian_buster1.vm.box = '../debian_buster.box'
		debian_buster1.vm.network 'private_network', ip: '192.168.100.2'
		debian_buster1.vm.network 'private_network', type: 'dhcp'
	end

	config.vm.define "debian_buster2" do |debian_buster2|
		debian_buster2.vm.hostname = 'debian02'
		debian_buster2.vm.box = '../debian_buster.box'
		debian_buster2.vm.network 'private_network', ip: '192.168.100.3'
		debian_buster2.vm.network 'private_network', type: 'dhcp'
	end

	config.vm.define "debian_buster3" do |debian_buster3|
		debian_buster3.vm.hostname = 'debian03'
		debian_buster3.vm.box = '../debian_buster.box'
		debian_buster3.vm.network 'private_network', ip: '192.168.100.4'
		debian_buster3.vm.network 'private_network', type: 'dhcp'
	end
end
