Vagrant.configure("2") do |config|
  (0..2).each do |i|
    config.vm.define "debian#{i + 1}" do |machine|
      machine.vm.provider "virtualbox" do |vb|
        vb.name = "debian#{i + 1}"
        vb.memory = 256
        vb.cpus = 1
      end

      machine.vm.hostname = "debian#{i + 1}"
      machine.vm.box = "debian_buster"

      machine.vm.network "forwarded_port", guest: 80, host: 8080 + i
      machine.vm.network "private_network", ip: "192.168.100.#{i + 2}"
      machine.vm.network "private_network", type: "dhcp"
      # config.vm.synced_folder ".", "/vagrant"

      machine.vm.provision "shell", inline: <<-SHELL
        cp /vagrant/sshd_config /etc/ssh/
        systemctl restart sshd

        cp /vagrant/sources.list /etc/apt/
        cp /vagrant/sudoers /etc/
        chmod -R 440 /etc/sudoers

        useradd -d /home/alvin -m -s /bin/bash -G sudo alvin
        (echo 'kkmouse'; echo 'kkmouse') | passwd alvin
      SHELL
    end
  end
end
