version: "3.9"
services:
  percona:
    image: percona
    container_name: percona
    restart: always
    env_file:
      - conf.env
    ports:
      - 3306:3306
    volumes:
      - percona_data:/var/lib/mysql
      - ./log:/var/log/mysql/
      - ./my.cnf:/etc/my.cnf:ro
    networks:
      - percona_network
volumes:
  percona_data:
networks:
  percona_network:
