version: "3.9"
services:
  # Zookper 集群
  zk01:
    image: zookeeper
    ports:
      - 2181:2181
    container_name: zk01
    networks:
      - zk_network
    privileged: true
    restart: always
    volumes:
      - zk_data1:/usr/local/zookeeper
    env_file:
      - config.env
    environment:
      - ZOO_MY_ID=1 # 当前实例的 ID
  zk02:
    image: zookeeper
    ports:
      - 2182:2181
    container_name: zk02
    networks:
      - zk_network
    privileged: true
    restart: always
    volumes:
      - zk_data2:/usr/local/zookeeper
    env_file:
      - config.env
    environment:
      - ZOO_MY_ID=2
volumes:
  zk_data1:
    driver_opts:
      type: tmpfs
      device: tmpfs
  zk_data2:
    driver_opts:
      type: tmpfs
      device: tmpfs
networks:
  zk_network:
    driver: bridge
