# 创建 Debian 虚拟机

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb| # 设定 virtualbox 配置
    vb.name = "debian1" # 虚拟机名称
    vb.memory = 256 # 内存大小
    vb.cpus = 1 # cpu 数量
  end

  config.vm.hostname = "debian1" # 虚拟机 hostname
  config.vm.box = "debian_buster" # 所使用的 vagrantbox 名称

  config.vm.define "debian1"

  # 网络配置
  config.vm.network "forwarded_port", guest: 80, host: 8080 # 端口转发配置
  config.vm.network "private_network", ip: "192.168.100.2" # 私有网络，固定 IP
  config.vm.network "private_network", type: "dhcp" # 私有网络，dhcp 分配

  # 设置共享目录
  # config.vm.synced_folder ".", "/vagrant"

  # 创建虚拟机时执行的脚本
  config.vm.provision "shell", inline: <<-SHELL
    cp /vagrant/sshd_config /etc/ssh/
    systemctl restart sshd

    cp /vagrant/sources.list /etc/apt/
    cp /vagrant/sudoers /etc/
    chmod -R 440 /etc/sudoers

    useradd -d /home/alvin -m -s /bin/bash -G sudo alvin
    (echo 'kkmouse'; echo 'kkmouse') | passwd alvin
  SHELL
end
