version: "3.7"
services:
  jenkinsci:
    image: "jenkinsci/blueocean"
    container_name: "jenkins-blueocean"
    volumes:
      - "data:/var/jenkins_home"
      - "certs:/certs/client:ro"
    ports:
      - "8080:8080"
      - "50000:50000"
    expose:
      - "8080"
      - "50000"
    environment:
      - "DOCKER_HOST=tcp://docker:2376"
      - "DOCKER_CERT_PATH=/certs/client"
      - "DOCKER_TLS_VERIFY=1"
    networks:
      - "jenkins_net"
networks:
  jenkins_net:
volumes:
  data:
    name: "study-devops-jenkins-data"
  certs:
    name: "study-devops-jenkins-certs"

