version: "3.9"

services:
  zk01:
    image: zookeeper
    container_name: zk01
    hostname: zk01
    privileged: true
    restart: always
    env_file:
      - ./env/zk.env
    environment:
      - ZOO_MY_ID=1 # zookeeper id
    volumes:
      - ./logs/zk01:/logs
      - zk01_data:/data
      - zk01_datalog:/datalog
    networks:
      - kafka_network
  zk02:
    image: zookeeper
    container_name: zk02
    hostname: zk02
    privileged: true
    restart: always
    env_file:
      - ./env/zk.env
    environment:
      - ZOO_MY_ID=2
    volumes:
      - ./logs/zk02:/logs
      - zk02_data:/data
      - zk02_datalog:/datalog
    networks:
      - kafka_network
  zk03:
    image: zookeeper
    container_name: zk03
    hostname: zk03
    privileged: true
    restart: always
    env_file:
      - ./env/zk.env
    environment:
      - ZOO_MY_ID=3
    volumes:
      - ./logs/zk03:/logs
      - zk03_data:/data
      - zk03_datalog:/datalog
    networks:
      - kafka_network
  kf01:
    image: bitnami/kafka
    container_name: kf01
    hostname: kf01
    privileged: true
    restart: always
    env_file:
      - ./env/kf.env
    environment:
      - KAFKA_CFG_BROKER_ID=1 # broker id
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,EXTERNAL://9094 # 本地监听 9092 端口，对外监听 9093 端口. 对外监听端口可以通过端口映射进行暴露
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kf01:9092,EXTERNAL://localhost:9094 # 该部分会注册到 zookeeper 里被集群其它节点或客户端发现
    volumes:
      - kf01_data:/bitnami
    networks:
      - kafka_network
    ports:
      - 9093:9093
    depends_on:
      - zk01
      - zk02
      - zk03
  kf02:
    image: bitnami/kafka
    container_name: kf02
    privileged: true
    restart: always
    env_file:
      - ./env/kf.env
    environment:
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,EXTERNAL://9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kf02:9092,EXTERNAL://localhost:9094
    volumes:
      - kf02_data:/bitnami
    networks:
      - kafka_network
    ports:
      - 9094:9093
    depends_on:
      - zk01
      - zk02
      - zk03
  kf03:
    image: bitnami/kafka
    container_name: kf03
    privileged: true
    restart: always
    env_file:
      - ./env/kf.env
    environment:
      - KAFKA_CFG_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,CONTROLLER://:9093,EXTERNAL://9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kf03:9092,EXTERNAL://localhost:9094
    volumes:
      - kf03_data:/bitnami
    networks:
      - kafka_network
    ports:
      - 9095:9093
    depends_on:
      - zk01
      - zk02
      - zk03
networks:
  kafka_network:
volumes:
  zk01_data:
  zk01_datalog:
  zk02_data:
  zk02_datalog:
  zk03_data:
  zk03_datalog:
  kf01_data:
  kf02_data:
  kf03_data:
