Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |vb|
		vb.name = "debian1"
		vb.memory = 256
		vb.cpus = 1
	end

	config.vm.hostname = "debian1"
	config.vm.box = "debian_buster"

	config.vm.define "debian1"
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.network "private_network", ip: "192.168.100.2"
	config.vm.network "private_network", type: "dhcp"
	# config.vm.synced_folder "~/share", "/home/vagrant/share"

	config.vm.provision "shell", inline: <<-SHELL
		cp /vagrant/sshd_config /etc/ssh/
		cp /vagrant/sources.list /etc/apt/
		cp /vagrant/sudoers /etc/
		chmod -R 440 /etc/sudoers

		useradd -d /home/alvin -m -s /bin/bash -G sudo alvin
		(echo 'kkmouse'; echo 'kkmouse') | passwd alvin
	SHELL
end
