Vagrant.configure("2") do |config|
	config.vm.provider "virtualbox" do |box|
		box.memory = 2048
		box.cpus = 1
	end

	config.vm.define "debian_buster" do |debian_buster|
		debian_buster.vm.hostname = 'debian01'
		debian_buster.vm.box = '../debian_buster.box'
		debian_buster.vm.network 'private_network', ip: '192.168.100.2'
		debian_buster.vm.network 'private_network', type: 'dhcp'
	end
end
