version: "3.9"
services:
  jenkins:
    image: jenkinsci/blueocean
    container_name: jenkins
    user: root
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    expose:
      - 8080
      - 50000
    networks:
      - jenkins_network
    restart: always
networks:
  jenkins_network:
volumes:
  jenkins_data:
