version: "3.9"
services:
  percona-master:
    image: percona/percona-server
    container_name: percona-master
    hostname: percona_master
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256M
        reservations:
          memory: 128M
    env_file:
      - ../env/percona.env
    ports:
      - 13306:3306
    volumes:
      - ./conf/master.cnf:/etc/my.cnf.d/master.cnf:ro # 设置 MySQL 配置文件
      - ./sql/master_setup.sql:/docker-entrypoint-initdb.d/master_setup.sql:ro # 设置数据库初始化脚步
      - ./log:/var/log/mysql
      - percona_master_data:/var/lib/mysql
    networks:
      - percona_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -uhealth | grep \"alvie\""
        ]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
  percona-slave:
    image: percona/percona-server
    container_name: percona-slave
    hostname: percona_slave
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256M
        reservations:
          memory: 128M
    depends_on:
      percona-master:
        condition: service_started
    env_file:
      - ../env/percona.env
    ports:
      - 23306:3306
    volumes:
      - ./conf/slave.cnf:/etc/my.cnf.d/slave.cnf:ro # 设置 MySQL 配置文件
      - ./sql/slave_setup.sql:/docker-entrypoint-initdb.d/slave_setup.sql:ro # 设置数据库初始化脚步
      - ./log:/var/log/mysql
      - percona_slave_data:/var/lib/mysql
    networks:
      - percona_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -uhealth | grep \"alvie\""
        ]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  percona_network:
volumes:
  percona_master_data:
  percona_slave_data:
