version: "3.9"
services:
  percona-master:
    image: percona/percona-server
    container_name: percona-master
    restart: always
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
        reservations:
          memory: 100M
    env_file:
      - conf.env
    ports:
      - 13306:3306
    volumes:
      - ./master_conf:/etc/my.cnf.d
      - percona_master_data:/var/lib/mysql
      - percona_master_log:/var/log/mysql
    networks:
      - percona_network
  percona-slave:
    image: percona/percona-server
    container_name: percona-slave
    restart: always
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
        reservations:
          memory: 100M
    env_file:
      - conf.env
    ports:
      - 23306:3306
    volumes:
      - ./slave_conf:/etc/my.cnf.d
      - percona_slave_data:/var/lib/mysql
      - percona_slave_log:/var/log/mysql
    networks:
      - percona_network
networks:
  percona_network:
volumes:
  percona_master_data:
  percona_master_log:
  percona_slave_data:
  percona_slave_log:
