---
version: "3"
services:
  nginx:
    image: "nginx:latest"
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "nginx_n"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./conf.d:/etc/nginx/conf.d"
      - "./log:/var/log/nginx"
      - "./www:/var/www"
    restart: "always"
networks:
  nginx_n:
