version: "3.9"

services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    privileged: true
    # 为启动命令增加参数, 指定 postgresql.conf 配置文件的实际存储位置
    command: >
      -c "config_file=/etc/postgresql/postgresql.conf"
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256M
        reservations:
          memory: 100M
    env_file:
      - ../env/pgsql.env
    ports:
      - 5432:5432
    volumes:
      # 映射配置文件
      - ./conf/postgres.conf:/etc/postgresql/postgresql.conf
      # 映射用于 WAL 日志归档的脚本文件
      - ./script/archive.sh:/etc/postgresql/archive.sh
      # 映射初始化脚本
      - ./script/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql:ro
      # 映射数据库数据存储路径
      - pgsql_data:/var/lib/postgresql/data
      # 映射 WAL 归档路径
      - pgsql_archive:/var/lib/postgresql/archive
    networks:
      - pgsql_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          # 检查 pgsql 的健康状态
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  pgsql_data:
  pgsql_archive:
networks:
  pgsql_network:
