version: "3.9"

services:
  postgres:
    image: postgres
    hostname: postgres
    container_name: postgres
    restart: always
    privileged: true
    ulimits:
      nproc: 65535
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 256M
        reservations:
          memory: 100M
    env_file:
      - ../env/pgsql.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
    ports:
      - 1486:1486
    volumes:
      - ../conf/postgres.conf:/etc/postgresql/postgresql.conf:ro
      - ./script/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql:ro
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - pgsql_network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  pgsql_data:
networks:
  pgsql_network:
