version: "3.9"

services:
  xtradb-01:
    image: percona/percona-xtradb-cluster
    container_name: pxc-01
    hostname: pxc_01
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          memory: 128M
    env_file:
      - ./env/xtradb.env
    volumes:
      - ./conf/xtradb-01.cnf:/etc/my.cnf.d/xtradb-01.cnf:ro # 设置 MySQL 配置文件
      - ./sql/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql:ro # 设置数据库初始化脚本
      - ./log:/var/log/mysql
      - pxc-01-data:/var/lib/mysql
    networks:
      - pxc-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -uhealth -e \"SHOW STATUS LIKE 'wsrep%'\" | grep 'wsrep_local_state_comment' | awk '{print $$2}' | grep -q 'Synced'"
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
  xtradb-02:
    image: percona/percona-xtradb-cluster
    container_name: pxc-02
    hostname: pxc_02
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          memory: 128M
    env_file:
      - ./env/xtradb.env
    environment:
      - CLUSTER_JOIN=pxc_01
    volumes:
      - ./conf/xtradb-02.cnf:/etc/my.cnf.d/xtradb-02.cnf:ro # 设置 MySQL 配置文件
      - ./log:/var/log/mysql
      - pxc-02-data:/var/lib/mysql
    networks:
      - pxc-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -uhealth -e \"SHOW STATUS LIKE 'wsrep%'\" | grep 'wsrep_local_state_comment' | awk '{print $$2}' | grep -q 'Synced'"
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
  xtradb-03:
    image: percona/percona-xtradb-cluster
    container_name: pxc-03
    hostname: pxc_03
    restart: always
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          memory: 128M
    env_file:
      - ./env/xtradb.env
    environment:
      - CLUSTER_JOIN=pxc_01
    volumes:
      - ./conf/xtradb-03.cnf:/etc/my.cnf.d/xtradb-03.cnf:ro # 设置 MySQL 配置文件
      - ./log:/var/log/mysql
      - pxc-03-data:/var/lib/mysql
    networks:
      - pxc-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysql -uhealth -e \"SHOW STATUS LIKE 'wsrep%'\" | grep 'wsrep_local_state_comment' | awk '{print $$2}' | grep -q 'Synced'"
        ]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 10s
volumes:
  pxc-01-data:
  pxc-02-data:
  pxc-03-data:
networks:
  pxc-network:
