# 配置 centos 服务器

Vagrant.configure("2") do |config|

  # 配置 virtualbox backend
	config.vm.provider "virtualbox" do |vb|
		vb.name = "centos1"
		vb.memory = 256
		vb.cpus = 1
	end

	config.vm.hostname = "centos1" # 设置 hostname
	config.vm.box = "centos_8" # 设置使用的 vagrantbox 名称

	# 网络配置
	config.vm.define "centos1"
	config.vm.network "forwarded_port", guest: 80, host: 8083 # 端口转发
	config.vm.network "private_network", ip: "192.168.100.5"  # 内网固定 IP
	config.vm.network "private_network", type: "dhcp" # 内网自动 IP

	# 设置共享目录
	# config.vm.synced_folder ".", "/vagrant"

	# 执行初始化脚本
	config.vm.provision "shell", inline: <<-SHELL
		cp /vagrant/sshd_config /etc/ssh/
    systemctl restart sshd

	 	mv /etc/yum.repos.d/CentOS-AppStream.repo /etc/yum.repos.d/CentOS-AppStream.repo.bak
		mv /etc/yum.repos.d/CentOS-Base.repo /etc/yum.repos.d/CentOS-Base.repo.bak
		mv /etc/yum.repos.d/CentOS-centosplus.repo /etc/yum.repos.d/CentOS-centosplus.repo.bak
		mv /etc/yum.repos.d/CentOS-Extras.repo /etc/yum.repos.d/CentOS-Extras.repo.bak
		mv /etc/yum.repos.d/CentOS-PowerTools.repo /etc/yum.repos.d/CentOS-PowerTools.repo.bak
		cp /vagrant/CentOS-Base.repo /etc/yum.repos.d/

	 	useradd -d /home/alvin -m -s /bin/bash alvin
	 	(echo 'kkmouse'; echo 'kkmouse') | passwd alvin

    echo "alvin	 ALL=(ALL) ALL" > /etc/sudoers.d/alvin
    chmod -R 440 /etc/sudoers.d/alvin
	SHELL
end
