---
# Define all dependencies between current role and other roles
# All tasks in dependencies role ("<dependency_role>/tasks/main.yml") should executed first
dependencies:
  # Dependency "common" role and pass parameter "common_param"
  - role: common
    vars:
      common_param: Common

  # Dependency "setup" role
  - role: setup
