---

# Demo of condition statements
- name: "Basic conditionals with when"
  hosts: 
    - "group_debian1"
    - "group_centos1"
  user: "alvin"
  connection: "ssh"
  tags: "G1"
  tasks:
    - name: "Run uname on 'Debian'"
      shell: "uname -sa"
      register: "debian_uname"
      when: "ansible_distribution == 'Debian'"
      
    - name: "Run uname on 'CentOS'"
      shell: "uname -sa"
      register: "centos_uname"
      when: "ansible_distribution == 'CentOS'"
      
    - name: "Show result"
      debug:
        msg: 
          - "{{ debian_uname.stdout | default('None') }}"
          - "{{ centos_uname.stdout | default('None') }}"
          
- name: "Conditionals based on ansible_facts"
  hosts: 
    - "group_debian1"
    - "group_centos1"
  user: "alvin"
  connection: "ssh"
  tags: "G2"
  tasks:
    - name: "Run uname on 'Debian' version 10"
      shell: "uname -sa"
      register: "debian10_uname"
      when: "ansible_facts['distribution'] == 'Debian' and (ansible_facts['distribution_major_version'] | int) >= 10"
      
    - name: "Run uname on 'Debian' version 9"
      shell: "uname -sa"
      register: "debian9_uname"
      when: "ansible_facts['distribution'] == 'Debian' and (ansible_facts['distribution_major_version'] | int) < 10"
      
    - name: "Run uname on 'CentOS' version 8"
      shell: "uname -sa"
      register: "centos8_uname"
      when: "ansible_facts['distribution'] == 'CentOS' and (ansible_facts['distribution_major_version'] | int) >= 8"
      
    - name: "Run uname on 'CentOS' version 7"
      shell: "uname -sa"
      register: "centos7_uname"
      when: "ansible_facts['distribution'] == 'CentOS' and (ansible_facts['distribution_major_version'] | int) < 8"
      
    - name: "Show result"
      debug:
        msg: 
          - "{{ debian10_uname.stdout | default('None') }}"
          - "{{ centos8_uname.stdout | default('None') }}"
          - "{{ debian9_uname.stdout | default('None') }}"
          - "{{ centos7_uname.stdout | default('None') }}"
          
- name: "Conditions based on registered variables"
  hosts: "group_debian1"
  user: "alvin"
  connection: "ssh"
  tags: "G3"
  tasks:
    - name: "Get 'uname -sa' result as register variable"
      shell: "uname -sa"
      register: "uname_result"
      
    - name: "Show register variable"
      debug:
        msg: "{{ uname_result }}"
        
    - name: "Show register variable 'stdout' propertiy"
      debug:
        msg: "{{ uname_result.stdout }}"
        
    - name: "Do operation on register variable"
      debug:
        msg: "Find 'Debian': {{ uname_result.stdout.find('Debian') >= 0 }}"

- name: "Condition base on operation result"
  hosts: "group_debian1"
  user: "alvin"
  connection: "ssh"
  tags: "G4"
  vars:
    cmd: "{{ lookup('env', 'CMD') or 'empty' }}"
  tasks:
    - name: "Get '{{ cmd }}' result as register variable"
      command: "{{ cmd }}"
      register: "cmd_result"
      ignore_errors: true
      when: "cmd != 'empty'"
      
    - name: "Get '{{ cmd }}' operation was skipped"
      debug: 
        msg: "command {{ cmd }} is skipped"
      when: "cmd_result is skipped"
      
    - name: "Show '{{ cmd }}' result if it run failed"
      debug: 
        msg: "{{ cmd_result.msg }}"
      when: "cmd_result is failed"
      
    - name: "Show '{{ cmd }}' result if it run succeeded"
      debug: 
        msg: "{{ cmd_result.stdout_lines }}"
      when: "cmd_result is succeeded and cmd_result.stdout_lines is defined"
