---

# Test ping for one remote server
- name: "Test availability of remote server"
  hosts: "group_debian1"
  user: "alvin"
  connection: "ssh"
  tasks:
    - name: "Ping remote server"
      ping:
      register: "ping_result"
    - name: "Show ping result"
      debug:
#       var: "ping_result"
        msg: "{{ ping_result.ping | default('None') }}"

# Test ping for all remote servers
- name: "Test availability of remote servers"
  hosts: "group_all"
  tasks:
    - name: "Ping remote server"
      ping:
      register: "ping_result"
    - name: "Show ping results"
      debug:
        msg: "{{ ping_result.ping | default('None') }}"