---

# Test ping for one remote server
- name: "Test availability of remote server"
  hosts: "group_debian1"
  user: "alvin"
  connection: "ssh"
# become: "yes"  # All task with become
  tasks:
    - name: "Ping remote server"
      ping:
      register: "ping_result"
      become: "yes"  # Current task with become
    - name: "Show ping result"
      debug:
        msg: "{{ ping_result.ping | default('None') }}"
