---

- name: Test task execute order
  hosts: group_debian1
  user: alvin
  connection: ssh
  gather_facts: False
  tags: G1
  pre_tasks:
    - name: pre-task executing
      shell: /usr/bin/true
  post_tasks:
    - name: post-task executing
      shell: /usr/bin/true
  tasks:
    - name: main task executing
      shell: /usr/bin/true
