---

# Test ansible variables

- name: "Test ansible variables"
  hosts: "group_debian1"
  user: "alvin"
  connection: "ssh"
  
  vars:
    - user_name: "Alvin"
    - home_page: "https://www.alvin.edu/ansible/playbook"
    
  tasks:
    - name: "Show some ansible variables"
      debug:
        msg:
          - "Default IPV4: {{ ansible_default_ipv4 }}"
          - "Architecture: {{ ansible_architecture }}"
          - "Distribution: {{ ansible_distribution }}"
          
    - name: "Show user define variables"
      debug:
        msg:
          - "User name: {{ user_name }}"
          - "Home page: {{ home_page }}"
          - "Variable A: {{ var_a | default('Unknown') }}"
          - "Variable B: {{ var_b | default('Unknown') }}"
          
    - name: "Include vars from file"
      include_vars: "vars/test_var.yml"
      
    - name: "Show user define variables again"
      debug:
        msg:
          - "User name: {{ user_name }}"
          - "Home page: {{ home_page }}"
          - "Variable A: {{ var_a | default('Unknown') }}"
          - "Variable B: {{ var_b | default('Unknown') }}"
          
    - name: "Show environment variables"
      debug:
        msg:
          - "Environment ENV_VAR: {{ lookup('env', 'ENV_VAR') }}"
          
    - name: "Run setup module"
      setup:
      register: "ansbile_variables"
      when: "lookup('env', 'SHOW_ALL') == 'true'"
      
    - name: "Show all nest ansible variables"
      debug:
        msg: "{{ ansbile_variables }}"
      when: "lookup('env', 'SHOW_ALL') == 'true'"
        
    - name: "Show ansible facts variables"
      debug:
        msg: "{{ ansible_facts }}"
      when: "lookup('env', 'SHOW_ALL') == 'true'"
  