---

version: '3'
services:
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - "mongo:/data/db"
      - "mongo:/data/configdb/"
    networks: 
      - "mongo"
networks: 
  mongo:
volumes: 
  mongo:
