version: "3.7"
services:
  es1:
    image: elasticsearch:8.5.2
    container_name: es1
    env_file:
      - conf.env
    environment:
      - node.name=es1
      - network.host=es1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es_network
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - es_log1:/usr/share/elasticsearch/logs
      - es_data1:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    privileged: true
  es2:
    image: elasticsearch:8.5.2
    container_name: es2
    env_file:
      - conf.env
    environment:
      - node.name=es2
    ports:
      - 9201:9200
      - 9301:9300
    networks:
      - es_network
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - es_log2:/usr/share/elasticsearch/logs
      - es_data2:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    privileged: true
  es3:
    image: elasticsearch:8.5.2
    container_name: es3
    env_file:
      - conf.env
    environment:
      - node.name=es3
    ports:
      - 9202:9200
      - 9302:9300
    networks:
      - es_network
    volumes:
      - ./plugins:/usr/share/elasticsearch/plugins
      - es_log3:/usr/share/elasticsearch/logs
      - es_data3:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    privileged: true
  kibana:
    image: kibana:8.5.2
    container_name: kibana
    depends_on:
      - es1
      - es2
      - es3
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=["http://es1:9200","http://es2:9200","http://es3:9200"]
      - I18N_LOCALE=en_US
    ports:
      - 15601:5601
    networks:
      - es_network
    restart: always
    privileged: true
networks:
  es_network:
volumes:
  es_data1:
  es_log1:
  es_data2:
  es_log2:
  es_data3:
  es_log3:
