---
version: "3"
services:
  neo4j:
    image: "neo4j:latest"
    container_name: "neo4j"
    volumes:
      - "data:/data"
      - "./conf:/var/lib/neo4j/conf"
      - "./logs:/logs"
      - "./import:/var/lib/neo4j/import"
      - "./plugins:/plugins"
    environment:
      - "NEO4J_AUTH=neo4j/neo4j_"
      - "NEO4J_dbms.security.auth_enabled=false"
    networks:
      - "newtork"
    ports:
      - "7474:7474"
      - "7687:7687"
      - "7473:7473"
networks:
  newtork:
volumes:
  data:
    name: "study-devops-neo4j"
