version: "3.9"

services:
  kafka:
    image: bitnami/kafka
    container_name: kafka
    hostname: kafka
    privileged: true
    restart: always
    environment:
      - BITNAMI_DEBUG=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    volumes:
      - kf_data:/bitnami/kafka
    networks:
      - kafka_network
    ports:
      - 9092:9092
networks:
  kafka_network:
volumes:
  kf_data:
