version: "3.9"

services:
  kafka:
    image: bitnami/kafka
    container_name: kafka
    hostname: kafka
    privileged: true
    restart: always
    environment:
      # - BITNAMI_DEBUG=yes
      - KAFKA_KRAFT_CLUSTER_ID=CsVKmlM_Q4eIzG7BXP6BnQ
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
    volumes:
      - kf_data:/bitnami
    networks:
      - kafka_network
    ports:
      - 19092:9092
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-metadata-quorum.sh --bootstrap-server localhost:9092 describe --status | grep ClusterId | awk '{print $$2}' | grep -q CsVKmlM_Q4eIzG7BXP6BnQ || exit 1"
        ]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
  kf_exporter:
    image: bitnami/kafka-exporter
    container_name: kf_exporter
    hostname: kf_exporter
    privileged: true
    restart: always
    command:
      - --kafka.server=kafka:9092
      - --web.listen-address=:9308
    networks:
      - kafka_network
    ports:
      - 9308:9308
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "timeout 5s bash -c ':>/dev/tcp/localhost/9308' || exit 1"
        ]
      interval: 1m
      timeout: 30s
      retries: 5
      start_period: 30s
networks:
  kafka_network:
volumes:
  kf_data:
