version: "3.9"
services:
  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
    env_file:
      - conf.env
    command: minio server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_net
    expose:
      - 9000
      - 9001
    ports:
      - 9000:9000
      - 9001:9001
networks:
  minio_net:
volumes:
  minio_data:
