global:
  # 拉取一次采样点数据的时间, 默认 1min
  scrape_interval: 15s
  # 评估一次规则的时间, 默认 1min
  evaluation_interval: 15s
  # 拉取超时, 默认 10s
  scrape_timeout: 10s

scrape_configs:
  - job_name: linux
    static_configs:
      - targets:
          - node_exporter:9100
        labels:
          instance: WSL
