{
 "title": "Custom Exporter Board",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   { "name": "demo_usage", "label": "demo_usage" }
  ]
 },
 "panels": [
  { "title": "Gauge Demo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "每小时平均调用次数",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "次" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(demo_some_resource_usage{job=\"custom-node-exporter\"}[1h])",
     "legendFormat": "调用次数"
    }
   ]
  },
  {
   "title": "使用量",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "次" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "demo_some_resource_usage{job=\"custom-node-exporter\"}",
     "legendFormat": "使用量"
    }
   ]
  },
  { "title": "Counter Demo", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "当前增长值",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "demo_function_call_times_total{job=\"custom-node-exporter\"}",
     "legendFormat": "当前增长值"
    }
   ]
  },
  {
   "title": "增长值",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 3, "y": 10 },
   "targets": [
    {
     "expr": "demo_function_call_times_total{job=\"custom-node-exporter\"}",
     "legendFormat": "增长值"
    }
   ]
  }
 ]
}