version: "3.7"
services:
  zk01:
    image: zookeeper:3.7.0
    container_name: zk01
    volumes:
      - zk_data1:/usr/local/zookeeper/data
    networks:
      - kafka_network
    ports:
      - 2181
    environment:
      - ZOO_MY_ID=1 # zookeeper id
      - ZOO_SERVERS=server.1=zk01:2888:3888;2181 server.2=zk02:2888:3888;2181 # zookeeper 集群情况
    privileged: true
    restart: always
  zk02:
    image: zookeeper:3.7.0
    container_name: zk02
    volumes:
      - zk_data2:/usr/local/zookeeper/data
    networks:
      - kafka_network
    ports:
      - 2181
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zk01:2888:3888;2181 server.2=zk02:2888:3888;2181
    privileged: true
    restart: always
  kf01:
    image: bitnami/kafka:3.0.0
    container_name: kf01
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_BROKER_ID=1 # broker id
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk01:2181,zk02:2181 # zookeeper 集群地址
      - ALLOW_PLAINTEXT_LISTENER=yes # 允许未加密的侦听器
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093 # 本地侦听地址
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kf01:9093 # 对外侦听地址，该地址会注册到 zookeeper 上被 kafka 集群共享
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true # 允许自动创建主题
      - KAFKA_CFG_LOG_RETENTION_HOURS=1 #
      - KAFKA_CFG_LOG_CLEARUP_POLICY=delete #
      - KAFKA_CFG_LOG_RETENTION_BYTES=536870912
      - KAFKA_CFG_LOG_SEGMENT_DELETE_DELAY_MS=60000 #
      - KAFKA_CFG_LOG_CLEANUP_INTERVAL_MINS=3 #
      - KAFKA_CFG_LOG_ROLL_HOURS=1 #
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=120000
      - KAFKA_CFG_SEGMENT_BYTES=536870913 #
      - KAFKA_CFG_RETENTION_MS=3600000
      - KAFKA_CFG_RETENTION_BYTES=536870912
      # - JMX_PORT=9999
    networks:
      - kafka_network
    volumes:
      - kf_data1:/bitnami/kafka
    depends_on:
      - zk01
      - zk02
  kf02:
    image: bitnami/kafka:3.0.0
    container_name: kf02
    ports:
      - 9093:9092
    environment:
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zk01:2181,zk02:2181 # zookeeper 集群地址
      - ALLOW_PLAINTEXT_LISTENER=yes # 允许未加密的侦听器
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093 # 本地侦听地址
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kf01:9093 # 对外侦听地址，该地址会注册到 zookeeper 上被 kafka 集群共享
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true # 允许自动创建主题
      - KAFKA_CFG_LOG_RETENTION_HOURS=1 #
      - KAFKA_CFG_LOG_CLEARUP_POLICY=delete #
      - KAFKA_CFG_LOG_RETENTION_BYTES=536870912
      - KAFKA_CFG_LOG_SEGMENT_DELETE_DELAY_MS=60000 #
      - KAFKA_CFG_LOG_CLEANUP_INTERVAL_MINS=3 #
      - KAFKA_CFG_LOG_ROLL_HOURS=1 #
      - KAFKA_CFG_LOG_RETENTION_CHECK_INTERVAL_MS=120000
      - KAFKA_CFG_SEGMENT_BYTES=536870913 #
      - KAFKA_CFG_RETENTION_MS=3600000
      - KAFKA_CFG_RETENTION_BYTES=536870912
      # - JMX_PORT=9999
    networks:
      - kafka_network
    volumes:
      - kf_data2:/bitnami/kafka
    depends_on:
      - zk01
      - zk02
networks:
  kafka_network:
    driver: bridge
volumes:
  zk_data1:
    driver_opts:
      type: tmpfs
      device: tmpfs
  zk_data2:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kf_data1:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kf_data2:
    driver_opts:
      type: tmpfs
      device: tmpfs
