version: "3.9"
services:
  zk01:
    image: zookeeper
    container_name: zk01
    volumes:
      - zk_data1:/data
      - zk_logs1:/logs
      - zk_datalog1:/datalog
    networks:
      - kafka_network
    ports:
      - 2181
    env_file:
      - zookeeper.env
    environment:
      - ZOO_MY_ID=1 # zookeeper id
    privileged: true
    restart: always
  zk02:
    image: zookeeper
    container_name: zk02
    volumes:
      - zk_data2:/data
      - zk_logs2:/logs
      - zk_datalog2:/datalog
    networks:
      - kafka_network
    ports:
      - 2181
    env_file:
      - zookeeper.env
    environment:
      - ZOO_MY_ID=2
    privileged: true
    restart: always
  kf01:
    image: bitnami/kafka
    container_name: kf01
    ports:
      - 9093:9093
    env_file:
      - kafka.env
    environment:
      - KAFKA_CFG_BROKER_ID=1 # broker id
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093 # 本地监听 9092 端口，对外监听 9093 端口. 对外监听端口可以通过端口映射进行暴露
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kf01:9092,EXTERNAL://localhost:9093 # 该部分会注册到 zookeeper 里被集群其它节点或客户端发现
    networks:
      - kafka_network
    volumes:
      - kf_data1:/bitnami/kafka
    depends_on:
      - zk01
      - zk02
  kf02:
    image: bitnami/kafka
    container_name: kf02
    ports:
      - 9094:9094
    env_file:
      - kafka.env
    environment:
      - KAFKA_CFG_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kf02:9092,EXTERNAL://localhost:9094
    networks:
      - kafka_network
    volumes:
      - kf_data2:/bitnami/kafka
    depends_on:
      - zk01
      - zk02
  kf03:
    image: bitnami/kafka
    container_name: kf03
    ports:
      - 9095:9095
    env_file:
      - kafka.env
    environment:
      - KAFKA_CFG_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kf03:9092,EXTERNAL://localhost:9095
    networks:
      - kafka_network
    volumes:
      - kf_data3:/bitnami/kafka
    depends_on:
      - zk01
      - zk02
networks:
  kafka_network:
    driver: bridge
volumes:
  zk_data1:
    driver_opts:
      type: tmpfs
      device: tmpfs
  zk_logs1:
    driver_opts:
      type: tmpfs
      device: tmpfs
  zk_datalog1:
    driver_opts:
      type: tmpfs
      device: tmpfs
  zk_data2:
    driver_opts:
      type: tmpfs
      device: tmpfs
  zk_logs2:
    driver_opts:
      type: tmpfs
      device: tmpfs
  zk_datalog2:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kf_data1:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kf_data2:
    driver_opts:
      type: tmpfs
      device: tmpfs
  kf_data3:
    driver_opts:
      type: tmpfs
      device: tmpfs
