version: "3.9"
services:
  es:
    image: elasticsearch:8.5.2
    container_name: es
    environment:
      - node.name=es
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.audit.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es_network
    volumes:
      - es_log:/usr/share/elasticsearch/logs
      - es_data:/usr/share/elasticsearch/data
      - ./plugins:/usr/share/elasticsearch/plugins
      # - ./elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    privileged: true
  kibana:
    image: kibana:8.5.2
    container_name: kibana
    depends_on:
      - es
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_HOSTS=["http://es:9200"]
      - I18N_LOCALE=en_US
      # - MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true
      # - ELASTICSEARCH_USERNAME=elastic
      # - ELASTICSEARCH_PASSWORD=dQUtviHdUCryzvBVLR8O
    ports:
      - 15601:5601
    networks:
      - es_network
    # volumes:
    #   - "./kibana.keystore:/usr/share/kibana/config/kibana.keystore"
    #   - "./kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    restart: always
    privileged: true
networks:
  es_network:
volumes:
  es_data:
  es_log:
