version: "3.7"
services:
  es:
    image: "elasticsearch:7.6.2"
    container_name: "es"
    environment:
      - "node.name=es"
      - "cluster.initial_master_nodes=es"
      - "cluster.name=docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "network"
    volumes:
      - "./logs:/usr/share/elasticsearch/logs/"
      - "./plugins:/usr/share/elasticsearch/plugins/"
      #   - "./config:/usr/share/elasticsearch/config:ro"
      - "data:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    restart: "always"
  kibana:
    image: "kibana:7.6.2"
    container_name: "kibana"
    depends_on:
      - "es"
    environment:
      - "SERVER_NAME=kibana"
      - "ELASTICSEARCH_HOSTS=http://es:9200"
    ports:
      - "5601:5601"
    networks:
      - "network"
    # volumes:
    #   - "./kibana.yml:/usr/share/kibana/config/kibana.yml:ro"
    restart: "always"
networks:
  network:
    driver: "bridge"
volumes:
  data:
    name: "study-devops-es-standalone-data"
