CREATE TABLE docker_feedback
(
    id         BIGINT AUTO_INCREMENT,
    title      VARCHAR(100) NOT NULL,
    content    VARCHAR(500) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    INDEX ix_name (title)
);
