logging:
  config: classpath:logback-spring.xml
  file:
    path: /logs

server:
  port: 8080
  servlet:
    context-path: /

spring:
  devtools:
    restart:
      enabled: false

  datasource:
    url: jdbc:h2:/data/prod;MODE=MYSQL;NON_KEYWORDS=USER
    username: sa
    password: sa~

  h2:
    console:
      enabled: false
