---
logging:
  config: 'classpath:logback-spring.xml'
  file:
    path: '/logs'

server:
  port: 8080
  servlet:
    context-path: '/'

spring:
  devtools:
    restart:
      enabled: false
  thymeleaf:
    cache: true

  datasource:
    url: 'jdbc:h2:file:/data/data;mode=mysql'
    username: 'sa'
    password: 'sa~'

  h2:
    console:
      enabled: false