version: "3.9"
services:
  java:
    image: study/java:1.0
    container_name: java
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
      - ./data:/data
    ports:
      - 8080:8080
