# docker run -it -p8080:8080 -v logs:/logs/ study/java:1.0
---
version: "3"
services:
  java:
    image: study/java:1.0
    container_name: 'java'
    volumes:
      - ./logs:/logs
      - ./data:/data
    ports:
      - "8080:8080"
