version: "3.9"
services:
  minio1:
    image: minio/minio:latest
    container_name: minio1
    volumes:
      - minio_data1:/data
    env_file:
      - conf.env
    command: minio server http://minio{1...4}/data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_net
    expose:
      - 9000
      - 9001
  minio2:
    image: minio/minio:latest
    container_name: minio2
    volumes:
      - minio_data2:/data
    env_file:
      - conf.env
    command: minio server http://minio{1...4}/data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: "30s"
      timeout: "20s"
      retries: 3
    networks:
      - minio_net
    expose:
      - 9000
      - 9001
  minio3:
    image: minio/minio:latest
    container_name: minio3
    volumes:
      - minio_data3:/data
    env_file:
      - conf.env
    command: minio server http://minio{1...4}/data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_net
    expose:
      - 9000
      - 9001
  minio4:
    image: minio/minio:latest
    container_name: minio4
    volumes:
      - minio_data4:/data
    env_file:
      - conf.env
    command: minio server http://minio{1...4}/data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - minio_net
    expose:
      - 9000
      - 9001
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx_log:/var/log/nginx
    ports:
      - 9000:9000
      - 9001:9001
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
    networks:
      - minio_net
networks:
  minio_net:
volumes:
  minio_data1:
  minio_data2:
  minio_data3:
  minio_data4:
