version: "3.9"
services:
  percona-master:
    image: percona
    container_name: percona-master
    restart: always
    env_file:
      - conf.env
    ports:
      - 13306:3306
    volumes:
      - percona_master_data:/var/lib/mysql
      - ./log-master:/var/log/mysql
      - ./master.cnf:/etc/my.cnf:ro
    networks:
      - percona_network
  percona-slave:
    image: percona
    container_name: percona-slave
    restart: always
    env_file:
      - conf.env
    ports:
      - 23306:3306
    volumes:
      - percona_slave_data:/var/lib/mysql
      - ./log-slave:/var/log/mysql
      - ./slave.cnf:/etc/my.cnf:ro
    networks:
      - percona_network
  proxysql:
    image: severalnines/proxysql
    container_name: proxysql
    restart: always
    environment:
      MONITOR_CONFIG_CHANGE: true
    ports:
      - 6033:6033
      - 6032:6032
      - 6080:6080
    volumes:
      - ./proxysql.cnf:/etc/proxysql.cnf:ro
      - ./proxysql:/var/lib/proxysql:rw
    networks:
      - percona_network
networks:
  percona_network:
volumes:
  percona_master_data:
  percona_slave_data:
